### ISSUE TITLE
下载示例程序运行报错

### ISSUE THREAD

**Issue by Bryant24s** [hackxhj/HighCopyTodayNews#3]
Cannot initialize a parameter of type 'void (^ _Nonnull)(NSErrorUserInfoKey  _Nonnull __strong, id  _Nonnull __strong, BOOL * _Nonnull)' with an rvalue of type 'void (^)(NSNumber *__strong, __strong id, BOOL * _Nonnull)'

**Comment by hackxhj** [comment]
最近如果有空 我来更新一下。。。

**Comment by Luckywannnnng** [comment]
同样的问题  android 党最新学ios这个项目运行也是报错   代码没法看

**Comment by rayliaorq** [comment]
请问什么时候更新？？ 我也遇到这个问题

**Comment by hackxhj** [comment]
已经解决编译错误。
